### ISSUE TITLE
Question: Must not be RGB

### ISSUE THREAD

**Issue by theChaosCoder** [dubhater/vapoursynth-motionmask#1]
Does that mean YCOCG is allowed? It crashes with YCOCG.

**Comment by theChaosCoder** [comment]
Strange, it crashes only with ftmc

`core.fmtc.matrix (clip, mat="601", col_fam=vs.YCOCG, bits=16) ` # also with GRAY, but YUV works, source is YV12 1080p

but this works perfectly
`clip = core.std.ShufflePlanes(clip, planes=[0, 1, 2], colorfamily=vs.YCOCG)`

motionmask is the first filter that crashes with fmtc ( I was testing several plugins for color space support)

**Comment by dubhater** [comment]
YCOCG should be allowed. Do you have a backtrace?

**Comment by theChaosCoder** [comment]
It just crashes without any error msg. Tested with vspipe and VS editor

**Comment by theChaosCoder** [comment]
I found the issue. It seems I have an older fmtc.dll. Now it's working also with ftmc.
